### ISSUE TITLE
BC Builder FMP support FUBAR

### ISSUE THREAD

**Issue by MikrySoft** [BuildCraft/BuildcraftCompat#32]
BC Builder doesn't place FMP blocks AT ALL. Having them in wrong orientation would be an improvement.
They are saved in the schematic, Builder shows them as required, they show up flying - just fail to place

Interesting log bit
```

[23:09:07] [Client thread/INFO] [inventorytweaks/]: buildcraft.builders.gui.ContainerBuilder
[23:09:10] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NullPointerException
[23:09:10] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at codechicken.microblock.MicroblockClass.createPart(MicroblockClass.scala:27)
[23:09:10] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at codechicken.microblock.MicroblockClass.createPart(MicroblockClass.scala:9)
[23:09:10] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at codechicken.multipart.MultiPartRegistry$.createPart(MultiPartRegistry.scala:220)
[23:09:10] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at codechicken.multipart.MultiPartRegistry.createPart(MultiPartRegistry.scala)
[23:09:10] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at buildcraft.compat.multipart.SchematicSimplePart.create(SchematicSimplePart.java:32)
[23:09:10] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at buildcraft.compat.multipart.SchematicSimplePart.placePart(SchematicSimplePart.java:20)
[23:09:10] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at buildcraft.compat.multipart.SchematicMultipartBlock.placeInWorld(SchematicMultipartBlock.java:122)
[23:09:10] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at buildcraft.core.builders.BuildingSlotBlock.writeToWorld(BuildingSlotBlock.java:71)
[23:09:10] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at buildcraft.core.builders.BuildingItem.build(BuildingItem.java:180)
[23:09:10] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at buildcraft.core.builders.BuildingItem.update(BuildingItem.java:135)
[23:09:10] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at buildcraft.core.builders.TileAbstractBuilder.func_145845_h(TileAbstractBuilder.java:100)
[23:09:10] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at buildcraft.builders.TileBuilder.func_145845_h(TileBuilder.java:579)
[23:09:10] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.world.World.func_72939_s(World.java:1939)
[23:09:10] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
[23:09:10] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
[23:09:10] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[23:09:10] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
[23:09:10] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[23:09:10] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

Full log: https://gist.github.com/MikrySoft/b96afae38aca00149f37
Blueprint: https://dl.dropboxusercontent.com/u/1383454/FMPTest-4354d4a69a75955f5133c3123ef0894d599fdaf7f03cea5fdafdab6d59c757ad.bpt

**Comment by MikrySoft** [comment]
@Chicken-Bones Downgrading FMP to 1.1.2.334 fixes the issue

**Comment by Chicken-Bones** [comment]
#35
