### ISSUE TITLE
[1.7]  Crash with NEI and BCC when looking up clock timer gate

### ISSUE THREAD

**Issue by asiekierka** [BuildCraft/BuildcraftCompat#73]
https://github.com/BuildCraft/BuildCraft/issues/3504

```
java.lang.ClassCastException: null not an ItemStack, ItemStack[] or List<ItemStack?
    at codechicken.nei.NEIServerUtils.extractRecipeItems(NEIServerUtils.java:344)
    at codechicken.nei.PositionedStack.<init>(PositionedStack.java:27)
    at buildcraft.compat.nei.RecipeHandlerIntegrationTable$CachedIntegrationTableRecipe.getResult(RecipeHandlerIntegrationTable.java:160)
    at codechicken.nei.recipe.TemplateRecipeHandler.getResultStack(TemplateRecipeHandler.java:498)
    at codechicken.nei.recipe.GuiRecipe.refreshSlots(GuiRecipe.java:232)
    at codechicken.nei.recipe.GuiRecipe.refreshPage(GuiRecipe.java:201)
```

**Comment by asiekierka** [comment]
Duplicate of #58
