### ISSUE TITLE
mt reload causes error when adding refinery recipe

### ISSUE THREAD

**Issue by ThePwnd** [BuildCraft/BuildcraftCompat#99]
Steps to reproduce:

1) Launch a Minecraft instance on 1.7.10 with MineTweaker3 v1.7.10-3.0.10, BuildCraft v7.1.23 or 7.1.24, and BuildCraft Compat v7.1.7 or 7.1.8
2) Create a new ZenScript file and add a new refinery recipe with the Refinery.addRecipe() method
3) Run `/mt reload` from in-game, verify the recipe has been registered
4) Run `/mt reload` from in-game again.

On step 4, you'll be greeted by an error in chat that says "An error occurred while processing this command."  Checking the game log, you might notice this error being thrown:

> [19:41:46] [Server thread/ERROR]: Couldn't process command: 'mt reload'
> java.lang.NullPointerException
> 	at buildcraft.compat.minetweaker.Refinery$AddRecipeAction.undo(Refinery.java:100) ~[Refinery$AddRecipeAction.class:?]
>	at minetweaker.runtime.MTTweaker.rollback(MTTweaker.java:88) ~[MTTweaker.class:?]
>	at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:621) ~[MineTweakerImplementationAPI.class:?]
>	at minetweaker.MineTweakerImplementationAPI$1.execute(MineTweakerImplementationAPI.java:83) ~[MineTweakerImplementationAPI$1.class:?]
>	at minetweaker.MineTweakerImplementationAPI$19.execute(MineTweakerImplementationAPI.java:642) ~[MineTweakerImplementationAPI$19.class:?]
>	at minetweaker.mc1710.server.MCServer$MCCommand.func_71515_b(MCServer.java:124) ~[MCServer$MCCommand.class:?]
>	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94) [z.class:?]
>	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739) [nh.class:?]
>	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718) [nh.class:?]
>	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) [ir.class:?]
>	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [ir.class:?]
>	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
>	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
>	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
>	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
>	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186) [bsx.class:?]
>	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
>	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]

**Comment by ThePwnd** [comment]
Hi @asiekierka , thanks for coming back to push a fix for this issue!  Any chance you're planning to publish a release of 7.1.9?  I don't see it in the Releases section on the repo, or on CurseForge.  I tried building it from the source myself, but I ran into errors.

**Comment by AlexIIL** [comment]
I'm responsible for publishing releases (not asie), but I've not been very prompt at doing that. Sorry!

**Comment by ThePwnd** [comment]
Hey @AlexIIL , all good!  I'm just super glad anyone came back to fix the issue at all.
